services:
  registry:
    image: registry
    container_name: registry
    networks:
      - udp_net
    ports:
      - "8080:8080/tcp"
    restart: unless-stopped

  node1:
    image: node
    container_name: node1
    env_file:
      - .env
    networks:
      - udp_net
    privileged: true
    ports:
      - "8081:8081/tcp"
    depends_on:
      - registry
    environment:
      SERVER_ADDRESS: registry:8080

  node2:
    image: node
    container_name: node2
    env_file:
      - .env
    networks:
      - udp_net
    privileged: true
    ports:
      - "8082:8081/tcp"
    depends_on:
      - registry
      - node1
    environment:
      SERVER_ADDRESS: registry:8080

  node3:
    image: node
    container_name: node3
    env_file:
      - .env
    networks:
      - udp_net
    privileged: true
    ports:
      - "8083:8081/tcp"
    depends_on:
      - registry
      - node1
      - node2
    environment:
      SERVER_ADDRESS: registry:8080

  node4:
    image: node
    container_name: node4
    env_file:
      - .env
    networks:
      - udp_net
    privileged: true
    ports:
      - "8084:8081/tcp"
    depends_on:
      - registry
      - node1
      - node2
      - node3
    environment:
      SERVER_ADDRESS: registry:8080

  node5:
    image: node
    container_name: node5
    env_file:
      - .env
    networks:
      - udp_net
    privileged: true
    ports:
      - "8085:8081/tcp"
    depends_on:
      - registry
      - node1
      - node2
      - node3
      - node4
    environment:
      SERVER_ADDRESS: registry:8080

networks:
  udp_net:
    driver: bridge