# Usa l'immagine base ufficiale di Go
FROM golang:1.22-alpine

# Imposta la cartella di lavoro nel container
WORKDIR /app

# Installa netem
RUN apk add --no-cache iproute2

# Copia i file del progetto nel container
COPY . .

# Compila il progetto e genera l'eseguibile
RUN GO111MODULE=off go build -o node .

# Definisci il comando di avvio
CMD ["./node"]
